### ISSUE TITLE
QGIS PostgreSQL connections are not updating in "Layer loader" dialog

### ISSUE THREAD

**Issue by pancost** [tudelft3d/3DCityDB-Tools-for-QGIS#26]
When adding a new db connection (or removing one), it is not updated at the "PostgreSQL existing connection" comboBox at the "Layer loader". At the other two ("Bulk deleter" "QGIS Package Administrator") the connection is updated as expected.

To recreate it:

(Adding new connection)
1. Make a clean installation of the plugin.
2. Open "QGIS Package Administrator"
3. Press "New Connection"
4. Add new connection credentials and click OK.
5. Check comboBox of existing connections at "Layer loader" (you should not be able to see the new connection)
5.1 Check comboBox of existing connections at "Bulk deleter" or "QGIS Package Administrator" (you should be able to see the new connection)

(Removing connection)
1. Check the existing connections comboBox "Layer loader"
2. Remove one of those connections (from QGIS)
3. Check again the existing connections comboBox "Layer loader". The connection that you removed is still there (and you can also connect to it - connection info are still stored in object inside the comboBox)

Ad hoc solution: Reload the plugin

**Comment by pancost** [comment]
Fixed in e516594

Make a couple of tests in all OSs and close this issue

**Comment by gioagu** [comment]
Solved in v. 0.8.4
