### ISSUE TITLE
User should not be able to import selecter layers if there are no selected layers.

### ISSUE THREAD

**Issue by pancost** [tudelft3d/3DCityDB-Tools-for-QGIS#42]
How to recreate:
1. Connect to a database with generated layers
2. In "Layers" tab -- the "Import selected layers" is disabled (expected correct behavior)
3. Select one of the available features -- the "Import selected Layers" is enabled (expected correct behavior)
![expected](https://github.com/tudelft3d/3DCityDB-Tools-for-QGIS/assets/66358285/a7f5e0b5-f282-4c7e-aeb2-75c261c1cb2e)

4. Set a different extent (e.g. click the "Set to layer extents" button) -- 
the previously selected available feature is unselected (expected correct behavior) HOWEVER  the "Import selected Layers" is still enabled (unexpected error-prone behavior)
![bug](https://github.com/tudelft3d/3DCityDB-Tools-for-QGIS/assets/66358285/8a94f40d-5337-457e-8318-488fb42f0831)

**Comment by gioagu** [comment]
Thanks, I could reproduce the bug.

Solved in v. 0.8.6
