### ISSUE TITLE
Changing user from rw to ro doesn't apply directly

### ISSUE THREAD

**Issue by pancost** [tudelft3d/3DCityDB-Tools-for-QGIS#56]
Tested Scenario (imagine Admin and user are different persons/computers):
Admin grants RW permissions to user X
User X load layer(s)
Admin wants to revoke all user X's permissions
User X still has its RW layer(s) on his project and he can STILL make changes and edits

We need to come with a plan to block user X's RW permissions
From the top of my head, in the server-side should be quite easy but for the client side I am not really sure what to do.
**I thinks this is a quite severe security risk**

The same scenario could be applies for the reverse situation:
User X starts with RO permissions until admin grants him RW.
User X still can't edit the layer(s) without deleting and loading from scratch.

**Comment by gioagu** [comment]
Yes, it needs some further reasoning, however it only applies once you change privileges "on the fly", i.e. with users still connected to the database?
Do I understand correctly?

**Comment by gioagu** [comment]
First thoughts:

1) From withing PostgreSQL, identify active connections belonging to which user.
2) Close those connections that belong to the user to be granted/revoked privileges
3) Change privileges.

select * from pg_stat_activity;

What do you think? Ideas?

**Comment by gioagu** [comment]
I could not reproduce your error. Here what I did:

1) Superuser grants user rw privileges.
2) In QGIS (via plugin), user connects, loads a layer, and starts editing it.
3) In the meanwhile, superuser revokes rw and grants ro privileges to user.
4) user, in QGIS, can still (apparently) "edit" the layer, but actually it is not possible anymore to store the edits. Which is what I expect. Of course, user won't find out till he/she tries to save the edits and it won't be possible. We may have a pissed-off user... :-)

The other way, ro to rw goes the same. So, this is not actually a security risk. It goes as it should, database side.
Of course it may be annoying for the user that may loose some edits, but this is another problem.

Tested with QGIS 3.34 and PostgreSQL 14, using the grant and revoke functions shipped with the QGIS Package (the same that are invoked by the QGIS Package Administrator).

Am I missing out something?

**Comment by pancost** [comment]
In my case in step 4 I am able to save and actually commit the changes to the database. 

I am pretty sure that the reason is the 'postgres' superuser status which I used to test this.

**Comment by gioagu** [comment]
OK, than this makes sense.
Superusers are not affected by the change of the privileges from the admin dialog, as they are... superusers.
So, it is indeed the expected behaviour. Therefore, not a bug!

And, as a general rule, you should use a superuser only for database management, never to do normal business! ;-)
